### ISSUE TITLE
Need spinning wheel wait for login to complete and grey out login button while waiting so don’t click twice

### ISSUE THREAD

**Issue by pfeairheller** [WebOfTrust/keep#103]
duplicate #93 ?

**Comment by shakedown-street** [comment]
The button was already disabled while the request is submitting, but the issue was that there is a 3 second timeout between when the request is successful and the task ending so that the agent has time to initialize/unlock fully before showing the main dashboard.  I've added a spinner that replaces the login button until that timeout ends the task.
